# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(645, 361)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setStyleSheet("font: 75 8pt \"Verdana\";\n"
"color: rgb(5, 113, 255);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.Customer = QtWidgets.QComboBox(Dialog)
        self.Customer.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Customer.setObjectName("Customer")
        self.gridLayout.addWidget(self.Customer, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setStyleSheet("font: 75 8pt \"Verdana\";\n"
"color: rgb(5, 113, 255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.PartNo = QtWidgets.QLineEdit(Dialog)
        self.PartNo.setObjectName("PartNo")
        self.gridLayout.addWidget(self.PartNo, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setStyleSheet("font: 75 8pt \"Verdana\";\n"
"color: rgb(5, 113, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.SerialNo = QtWidgets.QLineEdit(Dialog)
        self.SerialNo.setObjectName("SerialNo")
        self.gridLayout.addWidget(self.SerialNo, 2, 1, 1, 1)
        self.Okbtn = QtWidgets.QPushButton(Dialog)
        self.Okbtn.setObjectName("Okbtn")
        self.gridLayout.addWidget(self.Okbtn, 4, 2, 1, 1)
        self.CancelBtn = QtWidgets.QPushButton(Dialog)
        self.CancelBtn.setObjectName("CancelBtn")
        self.gridLayout.addWidget(self.CancelBtn, 4, 3, 1, 1)
        self.PopTable = QtWidgets.QTableWidget(Dialog)
        self.PopTable.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));")
        self.PopTable.setObjectName("PopTable")
        self.PopTable.setColumnCount(6)
        self.PopTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.PopTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.PopTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.PopTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.PopTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.PopTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.PopTable.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.PopTable, 3, 0, 1, 5)
        self.View_pop = QtWidgets.QPushButton(Dialog)
        self.View_pop.setStyleSheet("background-color: rgb(255, 202, 226);")
        self.View_pop.setObjectName("View_pop")
        self.gridLayout.addWidget(self.View_pop, 2, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Product Name:"))
        self.label_3.setText(_translate("Dialog", "Part No:"))
        self.label_2.setText(_translate("Dialog", "Serial No:"))
        self.Okbtn.setText(_translate("Dialog", "OK"))
        self.CancelBtn.setText(_translate("Dialog", "Cancel"))
        item = self.PopTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Code"))
        item = self.PopTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "SNo"))
        item = self.PopTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "SpareSno"))
        item = self.PopTable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "SparePartNo"))
        item = self.PopTable.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "LotNo"))
        item = self.PopTable.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Category"))
        self.View_pop.setText(_translate("Dialog", "View"))
