# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ui.log import Ui_Frame
from PyQt5.QtWidgets import QApplication, QMainWindow,QLineEdit,QMessageBox

from PyQt5 import QtCore
import sys
#from ui.pages.toyota_ui import Ui_Form
#from pages_functions.toyota import Toyota
from configparser import ConfigParser
from connection import Connection
import base64
class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.ui=Ui_Frame()
        self.ui.setupUi(self)
        #self.setWindowFlag(QtCore.Qt.WindowCloseButtonHint, False)
        self.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.login=self.ui.pushButton
        self.login.clicked.connect(self.Login)
        self.ex=self.ui.pushButton_2
        self.ex.clicked.connect( lambda: self.close())
        self.name=self.ui.lineEdit
        self.password=self.ui.lineEdit_2
        self.password.setEchoMode(QLineEdit.Password)
        self.name.setText("PRAGA")
        self.password.setText("123456")
        
        


     
    def Login(self):
        users={}
        username=self.name.text()
        password=self.password.text()
        pas=password.encode("ascii")
        base64_bytes = base64.b64encode(pas)
        con_pas = base64_bytes.decode("ascii")
        print(con_pas)
        conn=Connection().cursor
        conn.execute("select UserId,IdPassword from usermaster")
        result=conn.fetchall()
        for i in result:
            users.update({i[0]:i[1]})
        print(users)


        
        if self.name.text()=="" and self.password.text()=="":
            QMessageBox.critical(None,"Error","Please Enter User Name and Password")
        #elif self.name.text()=="admin" and self.password.text()=="admin":
        elif username in users and users[username] == con_pas:
            cf=ConfigParser()
            cf.read("Config.ini")
            
            cf["login"]["auth"]=str(self.name.text())
            with open('Config.ini', 'w') as configfile:    # save
                cf.write(configfile)
          
            from main import MyWindow
            #from pages_functions.toyota import Toyota
           
            
           
            
            
            self.win=QMainWindow()
            self.UI=MyWindow()
            self.win=self.UI
           
            
            
        
            self.win.show()
            #self.txt="admin"
            self.close()
        else:
            QMessageBox.critical(None,"Error","Wrong Username and Password")

        
            
        
            

        
                
        
        
if __name__ == '__main__':
    

    app = QApplication(sys.argv)

    window = Ui_MainWindow()
    window.show()

    sys.exit(app.exec())
        
